### ISSUE TITLE
PMMM中如何确定cstr限制的

### ISSUE THREAD

**Issue by gisguiser** [JHL-HUST/PMMM#2]
您好，请问下在您的代码中您是如何确定cstr的？

**Comment by MasterX666** [comment]
preprocess.py中的cstr是根据每个数据集的目标type确定的，其中每个数字表示传递途径，cstr中保留和目标type相关的途径。

例如在DBLP数据集中，edges.pkl中的邻接矩阵是按照顺序排列的，可打开查看。0表示PA，1表示AP，2表示PT，3表示TP，在实际运行中还会扩展单位矩阵I（4）和空矩阵（5），因此保留传递到目标type A的途径，cstr即为[1,4]。

> 您好，请问下在您的代码中您是如何确定cstr的？
