### ISSUE TITLE
运行acm时报错

### ISSUE THREAD

**Issue by cold-rivers** [JHL-HUST/PMMM#4]
python train_search.py --dataset ACM --steps 4 --eps 0.3 --seed 2 --lam_seq 0.8 --lam_res 0.8

    node_feats = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated

是数据集损坏了吗？

**Comment by MasterX666** [comment]
ACM数据在上传时损坏，目前已修正，感谢指出。

> python train_search.py --dataset ACM --steps 4 --eps 0.3 --seed 2 --lam_seq 0.8 --lam_res 0.8
> 
> ```
> node_feats = pickle.load(f)
> ```
> 
> _pickle.UnpicklingError: pickle data was truncated
> 
> 是数据集损坏了吗？
